---
name: "Authenticate to AWS for Deploy"

# Trigger when commits are pushed to the master branch

on:
  push:
    branches: [ $default-branch ]

jobs:

  cfn-deliver:
    name: Deliver CloudFormation
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1